### ISSUE TITLE
It should be possible not to use the visibility handler/visibility settings

### ISSUE THREAD

**Issue by PanzerLlama** [thephpleague/flysystem-google-cloud-storage#4]
GCP storage buckets now suggest not to use ACL but bucket wide permissions when possible. Unfortunately trying to upload a file to such bucket throws an error:

Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access

That was a problem for me, I ended up making a copy of the adapter since it was unable to extend it and just commented out the following line:

'predefinedAcl' => $this->visibilityHandler->visibilityToPredefinedAcl($visibility),

it would be good to actually allow null $defaultVisibility, $dafaultAcl with null works when doing uploads.

**Comment by jkuma** [comment]
We're facing the same issue here. Message "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled" is returned by GCP when trying to pass obsolete ACL.

Can we consider a patch in order to bypass _predefinedAcl_ option ?

**Comment by maksymvirchenko** [comment]
Will this issue be fixed one day? I don't really want to copy entire adapter just to comment 2 lines.

**Comment by sandrokeil** [comment]
I'm facing the same problem. Would be nice to make it configurable like implemented in #5

**Comment by rlcurrall** [comment]
I was able to get around the reported error by setting the `visibility` configuration like so:

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'gcloud'
            visibility: noPredefinedVisibility # This is the important line we added
            options:
                client: 'google_storage_client'
                bucket: '%env(DEFAULT_BUCKET)%'
```

**Comment by silverbackdan** [comment]
Hi, this is still an issue it seems when trying to use `copy` even with this config set.

It appears that this line will always be called to try and determine current visibility and therefore cause the ACL error:
https://github.com/thephpleague/flysystem-google-cloud-storage/blob/3.x/GoogleCloudStorageAdapter.php#L352

**Comment by johndodev** [comment]
> I ran into this issue in Symfony using the [Flysystem Bundle](https://github.com/thephpleague/flysystem-bundle) and was able to get around the reported error by setting the `visibility` to "noPredefinedVisibility" configuration like so:
> 
> ```yaml
> flysystem:
>     storages:
>         default.storage:
>             adapter: 'gcloud'
>             visibility: noPredefinedVisibility # This is the important line we added
>             options:
>                 client: 'google_storage_client'
>                 bucket: '%env(DEFAULT_BUCKET)%'
> ```
> 
> If you are using Flysystem without a framework, you can specify the `visibility` configuration in one of two ways:
> 
> ```
> // On construct of \League\Flysystem\Flilesystem
> $fs = new Filesystem($adapter, ['visibility' => 'noPredefinedVisibility']);
> 
> // As the final parameter to `write` or other method
> $fs->write('location', 'contents', ['visibility' => 'noPredefinedVisibility']);
> ```

This really should be somewhere in the documentation (and the copy error fixed).

**Comment by fvilpoix** [comment]
Here is a temporary configuration to have it work in Symfony, using a Compiler pass:

```yaml
   # services.yaml
    storage.google.visibility:
        class: League\Flysystem\GoogleCloudStorage\PortableVisibilityHandler
        arguments:
            - 'allUsers'
            - !php/const League\Flysystem\GoogleCloudStorage\PortableVisibilityHandler::NO_PREDEFINED_VISIBILITY
            - !php/const League\Flysystem\GoogleCloudStorage\PortableVisibilityHandler::NO_PREDEFINED_VISIBILITY
```

```php
<?php
// App\DependencyInjection\GoogleApiCompilerPass

declare(strict_types=1);

namespace App\DependencyInjection;

use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class GoogleApiCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        // set google bucket default visibility
        // fixes https://github.com/thephpleague/flysystem-google-cloud-storage/issues/4
        $container->getDefinition('flysystem.adapter.storage.google')->setArgument(
            2,
            new Reference('storage.google.visibility')
        );
    }
}
```

And add the compiler pass to your kernel or your bundle.
